---- MODULE MCExampleOpen ----
(* Generated by tools/generate_ledgers.py from example.json; do not edit. *)
EXTENDS Example

Reachable == {
    "Census"
}
EventuallyReachable == <>(established = Reachable)
====
