---- MODULE MCExampleGaloisAssumed ----
(* Generated by tools/generate_ledgers.py from example.json; do not edit. *)
EXTENDS Example

Reachable == {
    "Census",
    "Galois",
    "Proof"
}
EventuallyReachable == <>(established = Reachable)
====
