---- MODULE MCExampleImports ----
(* Generated by tools/generate_ledgers.py from example.json; do not edit. *)
EXTENDS Example

Reachable == {
    "Census",
    "Density",
    "Lemma",
    "Theorem"
}
EventuallyReachable == <>(established = Reachable)
====
