---- MODULE Example ----
(* Generated by proof_records/generate_ledgers.py from example.json; do not edit. *)
(* Repository: larsbx/finite-math-kernels (example). *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "Census",
    "Conditional",
    "Density",
    "Galois",
    "Lemma",
    "OnRetracted",
    "Proof",
    "Retracted",
    "Sweep",
    "Theorem",
    "WithinSweep"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "Census" -> {}
      [] r = "Conditional" -> {"Lemma", "Galois"}
      [] r = "Density" -> {}
      [] r = "Galois" -> {}
      [] r = "Lemma" -> {"Census", "Density"}
      [] r = "OnRetracted" -> {"Retracted"}
      [] r = "Proof" -> {}
      [] r = "Retracted" -> {}
      [] r = "Sweep" -> {}
      [] r = "Theorem" -> {"Lemma", "Proof"}
      [] r = "WithinSweep" -> {"Sweep"}]

ProvedDef == {
    "Census",
    "Conditional",
    "Lemma",
    "OnRetracted",
    "Proof",
    "Theorem",
    "WithinSweep"
}

ImportedDef == {
    "Density"
}

BoundedDef == {
    "Sweep"
}

WithdrawnDef == {
    "Retracted"
}

NoAssumptions == {}
ImportsAssumed == ImportedDef
GaloisAssumed == {
    "Galois"
}

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
CensusNotEstablished == "Census" \notin established
ConditionalNotEstablished == "Conditional" \notin established
DensityNotEstablished == "Density" \notin established
GaloisNotEstablished == "Galois" \notin established
LemmaNotEstablished == "Lemma" \notin established
OnRetractedNotEstablished == "OnRetracted" \notin established
ProofNotEstablished == "Proof" \notin established
RetractedNotEstablished == "Retracted" \notin established
SweepNotEstablished == "Sweep" \notin established
TheoremNotEstablished == "Theorem" \notin established
WithinSweepNotEstablished == "WithinSweep" \notin established

====
