#!/usr/bin/env python3
"""Write the ``orbit-census-v1`` golden vectors from the reference semantics.

Usage:
    make_orbit_vectors.py            rewrite fixtures/orbit_census_v1.txt
    make_orbit_vectors.py --check    exit 1 if the committed file has drifted

One tab-separated case per line; a record keeps its own single spaces:

    census            <record>            replay must accept; census must emit it
    tampered          <reason>  <record>  replay must answer <reason>
    request-malformed <field>   <p c cap lo hi>
    decode-malformed  <field>   <line>
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from orbit_census_reference import FIELDS, Block, census, encode, replay_verdict, tamper  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "fixtures" / "orbit_census_v1.txt"
HEADER = "# orbit-census-v1 golden vectors; generated by tools/make_orbit_vectors.py; do not edit"

#: Every boundary of section 7, then the Bend domain edge, then Mojo-only sizes.
BLOCKS = (
    Block(2, 0, 2, 0, 2), Block(2, 1, 2, 0, 2), Block(3, 0, 3, 0, 3), Block(5, 1, 5, 0, 5),
    Block(7, 3, 7, 0, 7), Block(7, 3, 0, 0, 7), Block(7, 3, 1, 0, 7), Block(7, 3, 2, 0, 7),
    Block(11, 0, 11, 0, 11), Block(13, 12, 13, 0, 13), Block(13, 5, 13, 4, 4), Block(13, 5, 13, 13, 13),
    Block(101, 7, 101, 0, 101), Block(101, 7, 9, 0, 101), Block(257, 255, 257, 0, 257),
    Block(1009, 2, 1009, 100, 700), Block(1009, 2, 40, 0, 1009),
    Block(4093, 1, 4093, 0, 4093), Block(4093, 4092, 60, 0, 4093), Block(4093, 17, 4093, 4000, 4093),
    Block(65537, 3, 65537, 0, 512), Block(16777213, 1, 16777213, 0, 4),
)

#: Blocks whose records are forged once per field; replay must name that field.
TAMPERED = (Block(7, 3, 7, 0, 7), Block(101, 7, 101, 0, 101))

MALFORMED_REQUESTS = (
    ("p", Block(1, 0, 1, 0, 1)), ("p", Block(9, 0, 9, 0, 9)), ("p", Block(4294967311, 0, 1, 0, 1)),
    ("c", Block(7, 7, 7, 0, 7)), ("cap", Block(7, 0, 2**32, 0, 7)),
    ("lo", Block(7, 0, 7, 5, 4)), ("hi", Block(7, 0, 7, 0, 8)),
)

OK = "orbit-census-v1 7 3 7 0 7"
MALFORMED_LINES = (
    ("arity", ""), ("arity", "orbit-census-v2 7 3 7 0 7 7 7 0 0 0 0 0 0 0"), ("arity", OK),
    ("arity", OK + " 7 7 0 0 0 0 0 0 0 0"), ("arity", OK + "  7 7 0 0 0 0 0 0 0"),
    ("p", "orbit-census-v1 07 3 7 0 7 7 7 0 0 0 0 0 0 0"), ("c", "orbit-census-v1 7 +3 7 0 7 7 7 0 0 0 0 0 0 0"),
    ("cap", "orbit-census-v1 7 3 4294967296 0 7 7 7 0 0 0 0 0 0 0"),
    ("n", "orbit-census-v1 7 3 7 0 7 -7 7 0 0 0 0 0 0 0"), ("w_lambda", "orbit-census-v1 7 3 7 0 7 7 7 0 0 0 0 0 0 x"),
    ("sum_mu", "orbit-census-v1 7 3 7 0 7 7 7 \u0661 0 0 0 0 0 0"),
)


def cases() -> list[str]:
    out = [HEADER]
    records = [(b, census(b)) for b in BLOCKS]
    out += [f"census\t{encode(b, a)}" for b, a in records]
    for b, a in ((b, a) for b, a in records if b in TAMPERED):
        for field in FIELDS:
            forged = tamper(a, field)
            out.append(f"tampered\t{replay_verdict(b, forged)}\t{encode(b, forged)}")
    out += [f"request-malformed\t{field}\t{' '.join(map(str, b))}" for field, b in MALFORMED_REQUESTS]
    out += [f"decode-malformed\t{field}\t{line}" for field, line in MALFORMED_LINES]
    return out


def render() -> str:
    return "\n".join(cases()) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if argv[1:] == ["--check"]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} has drifted; run tools/make_orbit_vectors.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
