#!/usr/bin/env python3
"""Write the ``orbit-census-v1`` golden vectors from the reference semantics.

Usage:
    make_orbit_vectors.py            rewrite fixtures/orbit_census_v1.txt
    make_orbit_vectors.py --check    exit 1 if the committed file has drifted

One tab-separated case per line; a record keeps its own single spaces:

    census            <record>            replay must accept; census must emit it
    tampered          <reason>  <record>  replay must answer <reason>
    request-malformed <field>   <p c cap lo hi>
    decode-malformed  <field>   <line>
    wide              <record>            decodes and re-encodes to itself

A ``wide`` record has a sum of 2^32 or more. Any such record costs at least
2^32 steps to recompute, so its truth is checked by the slow polyglot gate
(the Mojo kernel replays it), not by this generator.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from orbit_census_reference import FIELDS, Block, census, encode, replay_verdict, tamper  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "fixtures" / "orbit_census_v1.txt"
HEADER = "# orbit-census-v1 golden vectors; generated by tools/make_orbit_vectors.py; do not edit"

#: Every boundary of section 7; then 65521, the largest prime below 2^16, where
#: the Bend 2 challenger squares natively; seeds just past 2^16; 2^24 - 3 and
#: 16777259 on either side of the Mojo kernel's switch from a table to hashing;
#: 2^31 - 1; and the contract's edge 2^32 - 5 with seeds near p - 1 and a cap
#: that resolves some seeds and not others.
BLOCKS = (
    Block(2, 0, 2, 0, 2), Block(2, 1, 2, 0, 2), Block(3, 0, 3, 0, 3), Block(5, 1, 5, 0, 5),
    Block(7, 3, 7, 0, 7), Block(7, 3, 0, 0, 7), Block(7, 3, 1, 0, 7), Block(7, 3, 2, 0, 7),
    Block(11, 0, 11, 0, 11), Block(13, 12, 13, 0, 13), Block(13, 5, 13, 4, 4), Block(13, 5, 13, 13, 13),
    Block(101, 7, 101, 0, 101), Block(101, 7, 9, 0, 101), Block(257, 255, 257, 0, 257),
    Block(1009, 2, 1009, 100, 700), Block(1009, 2, 40, 0, 1009),
    Block(4093, 1, 4093, 0, 4093), Block(4093, 4092, 60, 0, 4093), Block(4093, 17, 4093, 4000, 4093),
    Block(65521, 0, 65521, 0, 65521), Block(65521, 1, 300, 0, 2048),
    Block(65537, 3, 65537, 0, 512), Block(65537, 0, 65537, 65472, 65537),
    Block(1048573, 7, 1048573, 0, 64), Block(8388593, 1, 8388593, 4194304, 4194336),
    Block(16777213, 1, 16777213, 0, 4), Block(16777213, 16777212, 16777213, 16777181, 16777213),
    Block(16777213, 5, 3000, 8000000, 8000064), Block(16777259, 2, 16777259, 0, 32),
    Block(2147483647, 3, 2147483647, 5, 13), Block(4294967291, 1, 4294967291, 0, 8),
    Block(4294967291, 4294967290, 4294967291, 4294967283, 4294967291),
    Block(4294967291, 12345, 120000, 2147483648, 2147483664),
)

#: Blocks whose records are forged once per field; replay must name that field.
TAMPERED = (Block(7, 3, 7, 0, 7), Block(101, 7, 101, 0, 101))

MALFORMED_REQUESTS = (
    ("p", Block(1, 0, 1, 0, 1)), ("p", Block(9, 0, 9, 0, 9)), ("p", Block(4294967311, 0, 1, 0, 1)),
    ("c", Block(7, 7, 7, 0, 7)), ("cap", Block(7, 0, 2**32, 0, 7)),
    ("lo", Block(7, 0, 7, 5, 4)), ("hi", Block(7, 0, 7, 0, 8)),
)

#: The first report of the 2^32 overflow: a full-field block in the Mojo domain
#: whose sum_lambda needs the widened range (4453414691 >= 2^32).
WIDE = ("orbit-census-v1 94379 0 94379 0 94379 94379 94379 47189 4453414691 47190 1 2 1 47188",)

#: Forged sums at and around the widened range: a value of 2^32 or more must
#: reach replay (a mismatch), not stop at decoding.
FORGED_SUMS = (("sum_mu", 2**32), ("sum_lambda", 2**63 - 1))

OK = "orbit-census-v1 7 3 7 0 7"
MALFORMED_LINES = (
    ("arity", ""), ("arity", "orbit-census-v2 7 3 7 0 7 7 7 0 0 0 0 0 0 0"), ("arity", OK),
    ("arity", OK + " 7 7 0 0 0 0 0 0 0 0"), ("arity", OK + "  7 7 0 0 0 0 0 0 0"),
    ("p", "orbit-census-v1 07 3 7 0 7 7 7 0 0 0 0 0 0 0"), ("c", "orbit-census-v1 7 +3 7 0 7 7 7 0 0 0 0 0 0 0"),
    ("cap", "orbit-census-v1 7 3 4294967296 0 7 7 7 0 0 0 0 0 0 0"),
    ("n", "orbit-census-v1 7 3 7 0 7 -7 7 0 0 0 0 0 0 0"), ("w_lambda", "orbit-census-v1 7 3 7 0 7 7 7 0 0 0 0 0 0 x"),
    ("sum_mu", "orbit-census-v1 7 3 7 0 7 7 7 \u0661 0 0 0 0 0 0"),
    ("sum_lambda", f"orbit-census-v1 7 3 7 0 7 7 7 6 {2**64} 3 1 1 2 3"),
    ("sum_mu", f"orbit-census-v1 7 3 7 0 7 7 7 {10**20} 21 3 1 1 2 3"),
    ("n", f"orbit-census-v1 7 3 7 0 7 {2**32} 7 6 21 3 1 1 2 3"),
    ("w_lambda", f"orbit-census-v1 7 3 7 0 7 7 7 6 21 3 1 1 2 {2**32}"),
)


def cases() -> list[str]:
    out = [HEADER]
    records = [(b, census(b)) for b in BLOCKS]
    out += [f"census\t{encode(b, a)}" for b, a in records]
    for b, a in ((b, a) for b, a in records if b in TAMPERED):
        for field in FIELDS:
            forged = tamper(a, field)
            out.append(f"tampered\t{replay_verdict(b, forged)}\t{encode(b, forged)}")
    b, a = records[BLOCKS.index(TAMPERED[0])]
    for field, value in FORGED_SUMS:
        forged = tamper(a, field, value - getattr(a, field))
        out.append(f"tampered\t{replay_verdict(b, forged)}\t{encode(b, forged)}")
    out += [f"request-malformed\t{field}\t{' '.join(map(str, b))}" for field, b in MALFORMED_REQUESTS]
    out += [f"decode-malformed\t{field}\t{line}" for field, line in MALFORMED_LINES]
    out += [f"wide\t{line}" for line in WIDE]
    return out


def render() -> str:
    return "\n".join(cases()) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if argv[1:] == ["--check"]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} has drifted; run tools/make_orbit_vectors.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
