#!/usr/bin/env python3
"""Write the cyclotomic-field-v1 golden vectors from the C1-Q2 Python reference.

Usage:
    make_cyclotomic_field_vectors.py            rewrite conformance/cyclotomic_field_v1.txt
    make_cyclotomic_field_vectors.py --check    exit 1 if the committed file has drifted

The Mojo kernel (kernel/cyclotomic) replays every line; the reference uses
recursive division for Phi_q and extended Euclid for inverses, the kernel the
Moebius product and the norm, so agreement is evidence rather than a copy.

Encoding (tab-separated, one case per line); an element is its rational
coordinates on 1, zeta, ..., zeta^(phi(q)-1), space-separated:
    phi    q  coefficients of Phi_q (integers, low -> high)
    mul    q  a  b  a*b
    inv    q  a  1/a | rejected
    aut    q  e  a  sigma_e(a) | rejected
    bytes  q  a  canonical bytes (hex)
    germ   q  p  P(0)  [w^q] 1/P  canonical bytes of [w^q] 1/P (hex), lambda = zeta_q^p
"""

from __future__ import annotations

import random
import sys
from fractions import Fraction
from math import gcd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "reference"))

from cyclotomic_reference import (  # noqa: E402
    automorphism, canonical_bytes, cyclotomic, cyclotomic_polynomial, inverse, is_zero, mul, parabolic_factor, phi,
    reciprocal_series_coefficient, zeta_power,
)

OUT = ROOT / "conformance/cyclotomic_field_v1.txt"
HEADER = "# cyclotomic-field-v1 golden vectors; generated by tools/make_cyclotomic_field_vectors.py; do not edit"
SEED = 0x43594331
CONDUCTORS = range(1, 13)
GERM_MAX = 8
CASES = 4


def element(q: int, rng: random.Random):
    zero_row = rng.random() < 0.1
    return cyclotomic(q, [Fraction(0) if zero_row else Fraction(rng.randint(-9, 9), rng.randint(1, 5)) for _ in range(phi(q))])


def enc(a) -> str:
    return " ".join(str(c) for c in a.coefficients)


def lines() -> list[str]:
    rng = random.Random(SEED)
    out = [HEADER]
    for q in CONDUCTORS:
        out.append(f"phi\t{q}\t" + " ".join(str(c) for c in cyclotomic_polynomial(q)))
    for q in CONDUCTORS:
        for _ in range(CASES):
            a, b = element(q, rng), element(q, rng)
            out.append(f"mul\t{q}\t{enc(a)}\t{enc(b)}\t{enc(mul(a, b))}")
            out.append(f"inv\t{q}\t{enc(a)}\t" + ("rejected" if is_zero(a) else enc(inverse(a))))
            e = rng.randint(-q, 2 * q)
            out.append(f"aut\t{q}\t{e}\t{enc(a)}\t" + (enc(automorphism(a, e)) if gcd(e, q) == 1 else "rejected"))
            out.append(f"bytes\t{q}\t{enc(a)}\t{canonical_bytes(a).hex()}")
    for q in range(1, GERM_MAX + 1):
        for p in [1] if q == 1 else [p for p in range(1, q) if gcd(p, q) == 1]:
            factor = parabolic_factor(zeta_power(q, p), q)
            coefficient = reciprocal_series_coefficient(factor, q)
            out.append(f"germ\t{q}\t{p}\t{enc(factor[0])}\t{enc(coefficient)}\t{canonical_bytes(coefficient).hex()}")
    return out


def render() -> str:
    return "\n".join(lines()) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} has drifted; rerun tools/make_cyclotomic_field_vectors.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
