#!/usr/bin/env python3
"""Write the projective-limits-v1 golden vectors from the Python reference.

Usage:
    make_projective_limits_vectors.py            rewrite conformance/projective_limits_v1.txt
    make_projective_limits_vectors.py --check    exit 1 if the committed file has drifted

Encoding (tab-separated, one case per line):
    rational   "p" or "p/q"          point      rational | "inf" | "rejected"
    poly       rationals low -> high, space-separated ("0" for zero)
    poly2      "i,j,c" monomials, ";"-separated

    limit        num  den  point  expected
    tangent      x    y    t0     expected
    asymptote    num  den  slope  intercept
    directional  num2 den2 direction expected
    curve        num2 den2 x  y   expected
    witness      num2 den2 search first first_limit second second_limit   ("none" x4 when not found)
    mobius       a b c d  point  expected
    chordal      p    q    expected
"""

from __future__ import annotations

import random
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "reference"))

from projective_limits_reference import (  # noqa: E402
    INFINITY, P1, Poly, Poly2, affine, asymptote, chordal_distance_squared, curve_limit, directional_limit,
    mobius_apply, mul, path_dependence_witness, poly, rational_limit, tangent_slope,
)

OUT = ROOT / "conformance/projective_limits_v1.txt"
HEADER = "# projective-limits-v1 golden vectors; generated by tools/make_projective_limits_vectors.py; do not edit"
SEED = 0x50524F4A


def q_text(value: Fraction) -> str:
    return str(Fraction(value))


def point_text(value: P1 | None) -> str:
    return "rejected" if value is None else "inf" if value == INFINITY else q_text(value[0])


def poly_text(p: Poly) -> str:
    return " ".join(map(q_text, p)) or "0"


def poly2_text(p: Poly2) -> str:
    return ";".join(f"{i},{j},{q_text(c)}" for i, j, c in p)


def mono(i: int, j: int, c: int = 1) -> tuple[int, int, Fraction]:
    return (i, j, Fraction(c))


def row(kind: str, *fields: str) -> str:
    return "\t".join((kind, *fields))


def limit_rows(rng: random.Random) -> list[str]:
    hand = [
        (poly(1, 0, 1), poly(-2, 1), affine(3)),
        (poly(1), poly(0, 1), affine(0)),
        (poly(1), poly(0, 1), INFINITY),
        (poly(7, 0, 3), poly(1, 5, 2), INFINITY),
        (poly(0, 0, 0, 1), poly(1, 1), INFINITY),
        (poly(-1, 0, 1), poly(-1, 1), affine(1)),
        (poly(2, -3, 0, 1), poly(1, -2, 1), affine(1)),
        (poly(), poly(1, 1), affine(2)),
        (poly(1, 1), poly(), affine(2)),
        (poly(), poly(), affine(2)),
    ]
    randoms = []
    for _ in range(120):
        root = Fraction(rng.randint(-4, 4), rng.randint(1, 3))
        common = mul(poly(-root, 1), poly(-root, 1)) if rng.random() < 0.3 else poly(-root, 1)
        p = mul(poly(*(rng.randint(-3, 3) for _ in range(rng.randint(1, 4)))), common)
        q = mul(poly(*(rng.randint(-3, 3) for _ in range(rng.randint(1, 4)))), common)
        point = rng.choice([affine(root), affine(root), INFINITY, affine(rng.randint(-3, 3))])
        if p or q:
            randoms.append((p, q, point))
    return [
        row("limit", poly_text(p), poly_text(q), point_text(at), point_text(rational_limit(p, q, at)))
        for p, q, at in hand + randoms
    ]


def tangent_rows(rng: random.Random) -> list[str]:
    hand = [
        (poly(0, 1), poly(0, 0, 0, 1), Fraction(2)),
        (poly(0, 0, 0, 1), poly(0, 1), Fraction(0)),
        (poly(0, 0, 1), poly(0, 0, 0, 1), Fraction(0)),
        (poly(0, 0, 0, 1), poly(0, 0, 1), Fraction(0)),
    ]
    randoms = [
        (poly(*(rng.randint(-3, 3) for _ in range(4))), poly(*(rng.randint(-3, 3) for _ in range(4))),
         Fraction(rng.randint(-2, 2)))
        for _ in range(40)
    ]
    return [
        row("tangent", poly_text(x), poly_text(y), q_text(t0), point_text(tangent_slope(x, y, t0)))
        for x, y, t0 in hand + randoms
        if tangent_slope(x, y, t0) is not None
    ]


def asymptote_rows(rng: random.Random) -> list[str]:
    hand = [(poly(1, 0, 1), poly(-1, 1)), (poly(2, 3), poly(5, 1)), (poly(0, 0, 0, 1), poly(1, 1))]
    randoms = []
    for _ in range(40):
        q = poly(*(rng.randint(-3, 3) for _ in range(rng.randint(2, 3))), rng.choice([-2, -1, 1, 2]))
        p = poly(*(rng.randint(-3, 3) for _ in range(rng.randint(1, len(q) + 2))))
        randoms.append((p, q))
    return [
        row("asymptote", poly_text(p), poly_text(q), *map(point_text, asymptote(p, q)))
        for p, q in hand + randoms
    ]


XY: Poly2 = (mono(1, 1),)
X2_PLUS_Y2: Poly2 = (mono(2, 0), mono(0, 2))
X2Y: Poly2 = (mono(2, 1),)
X4_PLUS_Y2: Poly2 = (mono(4, 0), mono(0, 2))
QUOTIENTS = [
    (XY, X2_PLUS_Y2),
    (X2Y, X2_PLUS_Y2),
    (X2Y, X4_PLUS_Y2),
    ((mono(2, 0, 1), mono(0, 2, -1)), X2_PLUS_Y2),
    ((mono(3, 0), mono(1, 2, 2)), (mono(1, 0), mono(0, 1, 3))),
    ((mono(1, 0), mono(0, 1)), (mono(1, 0), mono(0, 1, -1))),
]


def bivariate_rows() -> list[str]:
    directions = [INFINITY, *(affine(Fraction(t, d)) for t in range(-3, 4) for d in (1, 2))]
    arcs = [(poly(0, 1), poly(0, 0, 1)), (poly(0, 0, 1), poly(0, 1)), (poly(0, 1), poly(0, 1, 1)), (poly(1, 1), poly(0, 1))]
    out = [
        row("directional", poly2_text(n), poly2_text(d), point_text(v), point_text(directional_limit(n, d, v)))
        for n, d in QUOTIENTS for v in directions
    ]
    out += [
        row("curve", poly2_text(n), poly2_text(d), poly_text(x), poly_text(y), point_text(curve_limit(n, d, x, y)))
        for n, d in QUOTIENTS for x, y in arcs
    ]
    for n, d in QUOTIENTS:
        for search in (1, 4):
            w = path_dependence_witness(n, d, search)
            fields = ("none",) * 4 if w is None else tuple(map(point_text, w))
            out.append(row("witness", poly2_text(n), poly2_text(d), str(search), *fields))
    return out


def mobius_rows(rng: random.Random) -> list[str]:
    out = []
    for _ in range(60):
        m = tuple(Fraction(rng.randint(-4, 4)) for _ in range(4))
        at = rng.choice([INFINITY, affine(Fraction(rng.randint(-5, 5), rng.randint(1, 4)))])
        out.append(row("mobius", " ".join(map(q_text, m)), point_text(at), point_text(mobius_apply(m, at))))
    return out


def chordal_rows(rng: random.Random) -> list[str]:
    def point() -> P1:
        return rng.choice([INFINITY, affine(Fraction(rng.randint(-6, 6), rng.randint(1, 5)))])

    pairs = [(affine(0), INFINITY), (affine(0), affine(1)), (affine(3), INFINITY)]
    pairs += [(point(), point()) for _ in range(60)]
    return [row("chordal", point_text(a), point_text(b), q_text(chordal_distance_squared(a, b))) for a, b in pairs]


def cases() -> list[str]:
    rng = random.Random(SEED)
    return [
        HEADER, *limit_rows(rng), *tangent_rows(rng), *asymptote_rows(rng), *bivariate_rows(),
        *mobius_rows(rng), *chordal_rows(rng),
    ]


def render() -> str:
    return "\n".join(cases()) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if argv[1:] == ["--check"]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} has drifted; run tools/make_projective_limits_vectors.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
